### ISSUE TITLE
Component available to support encoding of map from tuple list

### ISSUE THREAD

**Issue by danj3** [michalmuskala/jason#100]
Hi,
I've put together a component [jason_tuple_list](https://github.com/danj3/jason_tuple_list) that allows a map to be constructed from a tuple list (more than a Keyword list since strings keys are necessary). I would publish it to hex but it depends on the unreleased master of jason.

The code is effectively trivial, but it formalizes an earlier issue and could be added as a dep and used.

For now, the following is required to make it a dep:
{ :jason_tuple_list, github: "danj3/jason_tuple_list" }

This will currently drag in the master version of Jason.

It's not a pretty scenario not being able to publish to hex since a lot of things depend on Jason and the necessary override.

**Comment by michalmuskala** [comment]
Yes, I intend to release the next version soon. Please give me couple days.

**Comment by michalmuskala** [comment]
I'm sorry it took quite a bit longer, but `1.2.0` with `Jason.Encode.keyword/2` is published.
