### ISSUE TITLE
Support exposing the position when tokenizing

### ISSUE THREAD

**Issue by uhrobots** [michalmuskala/jason#116]
This may be a bit of an special case, but it would be fantastic if I could somehow get access to the parser's position as it decodes a JSON string. One potential use case would be pointing out issues with JSON object structure in another library (such as parsing a standardized format defined by a JSON schema file.) The positions only seem to be exposed when the parser encounters an error.

Perhaps a custom middleware-like interface that provides a configurable callback function after successfully parsing a token that passes in the token, and position?

**Comment by michalmuskala** [comment]
I agree this could be very useful, unfortunately I don't really see how such a flexible interface could be combined with the performance-focused nature of jason.

**Comment by michalmuskala** [comment]
I'm going to close this issue. If there are any suggestions how this could be handled, please reopen the issue.
