### ISSUE TITLE
Arrays aren't decoded

### ISSUE THREAD

**Issue by lpender** [michalmuskala/jason#131]
Hi! Thanks for your great library.

Here's what I'm working with in Elixir:

```
point = "{\"type\":\"Point\",\"coordinates\":[10,10]}"
Jason.decode!(point)
# %{"coordinates" => '\n\n', "type" => "Point"}
```

As you can see, the coordinates are lost.

Here's what happens when I do something similar in JS

```
const point = "{\"type\":\"Point\",\"coordinates\":[10,10]}"
JSON.parse(point)
# {"coordinates" => [10,10], "type" => "Point"}
```

Tried with Jason 1.0, 1.2

**Comment by michalmuskala** [comment]
This is a behaviour of Elixir in general, and is related to how things are printed in the shell. In particular in Elixir `[10, 10] === '\n\n'`. Elixir prints lists of integers in printable range as charlists.

See more here: https://github.com/elixir-lang/elixir/wiki/FAQ#4-why-is-my-list-of-integers-printed-as-a-string

**Comment by lpender** [comment]
Thanks
