### ISSUE TITLE
Report on JSON Interoperability—Duplicate Key Handling 

### ISSUE THREAD

**Issue by halostatue** [michalmuskala/jason#132]
I was reading an interesting article on [JSON interoperability vulnerabilities](https://labs.bishopfox.com/tech-blog/an-exploration-of-json-interoperability-vulnerabilities) from Bishop Fox Labs and Jason was one of the tested libraries.

It might be useful to allow the decoder to choose between `first-key` or `last-key` on duplicate keys during parsing; I’m not sure how this would be configured in something like Phoenix, Ecto, or Absinthe, but given some of the issues mentioned in the article, this _may_ be worth pursuing.

**Comment by michalmuskala** [comment]
With 7e25ebb8ecf11bf959f805a767661f1c24c2a8fa this can be handled at application level by decoding with the option `objects: :ordered_objects` and explicitly picking which element to use or to outright error in case of duplicates.
