### ISSUE TITLE
[QUESTION] Jason with UTF-8 characters

### ISSUE THREAD

**Issue by at88mph** [michalmuskala/jason#141]
I have a Phoenix 1.6 app that is proxying JSON requests from a different domain.  Some of the JSON coming in contains extended ASCII (French) characters:

```json
{"name": "abcdé"}
```

And my controller is simply pulling it in and sending it back out again:

```
    def get(conn, _params) do
      url = "https://..."
      response = HTTPoison.get!(url)
      conn |> halt |> json response.body
    end
```

My Phoenix app is using Jason by default, but the JSON cannot be encoded on the way out:

```
(Jason.EncodeError) invalid byte 0xE9 in \"{\"name\": \"abcdé\"}\"
```

Can Jason be told to re-encode extended characters?

**Comment by michalmuskala** [comment]
UTF-8 is handled correctly, as JSON is defined by standards to basically work only on UTF-8 text.

Your description, however, makes it sound like the returned encoding is `latin1` (judging from the `0xE9` byte, UTF-8 does not contain standalone bytes like that), which is not handled by this library (and I'd assume many other libraries).

In particular, this works just fine, when input is indeed UTF-8: 
```
iex(1)> Jason.decode!(~S|{"name": "abcdé"}|)
%{"name" => "abcdé"}
```

You can always try transcoding the encoding of the string with `:unicode.characters_to_binary(data, latin1, utf8)`, if you know the `data` is indeed in `latin1`.

**Comment by at88mph** [comment]
That was exactly what I needed.  Many thanks.
