### ISSUE TITLE
Decode failing when string has lots of spaces and special characters

### ISSUE THREAD

**Issue by ricardoruwer** [michalmuskala/jason#148]
I'm working on a task to migrate from `Poison` to `Jason` but I found an issue when trying to decode a GraphQL query on our regressions tests, basically, someone just copied and pasted it from somewhere and the string has a lot of spaces, tabs, and other special characters, but it was working with `Poison` and now it is failing with `Jason`.

How to reproduce:

```ex
json = "{ \"query\": \"mutation updateSomethingAccount ($something_account: SomethingInput!)\r\n     { updateSomethingAccount(somethingAccount: $something_account)  \r\n            {isDefault    \r\n             id\r\n            email}}\", \t\r\n     \"variables\": { \r\n\t\t \t\"something_account\": {\r\n \t\t                      \"nonce\": \"fake-something-billing-agreement-nonce\",\r\n                                      \"isDefault\": true}}, \t\r\n\"operationName\": \"updateSomethingAccount\" }"
```
```ex
Poison.decode json
# => {:ok, ...}

Jason.decode json
# => {:error, %Jason.DecodeError{...}}
```

**Comment by michalmuskala** [comment]
The JSON does look invalid [according to spec](https://datatracker.ietf.org/doc/html/rfc8259#section-7) - in particular, raw `\n` and `\r` bytes are not allowed - they have to be escaped (producing `\\n` and `\\r` in string representation).

The full error message also indicates directly the issue with the `\r` byte:
```
Jason.decode! json
** (Jason.DecodeError) unexpected byte at position 81: 0xD ("\r")
    (jason 1.3.0) lib/jason.ex:92: Jason.decode!/2
```

This strictness in Jason is called out in README in the [differences to Poison section](https://github.com/michalmuskala/jason#differences-to-poison). In this case Poison does not adhere to the standard, which might have various unexpected implications. As such I don't plan on changing the behaviour in Jason.
