### ISSUE TITLE
Jason.Decoder is not a protocol

### ISSUE THREAD

**Issue by amplexdenmark** [michalmuskala/jason#150]
Hi

I'm trying to change code that uses Poison into using Jason.

And has come upon constructs like this:
`defimpl Poison.Decoder, for: CMSAPI.Model.Attribute do
  def decode(value, _options) do ...
`
Just replacing `Poison` with `Jason` in this snippet leads to this compile error:
`** (ArgumentError) Jason.Decoder is not a protocol`

Now looking at the code for 'Jason.Decoder' sure enough it is not a protocol, but `Jason.Encoder` is.

Is this deliberate? or an oversight?

Do you have a suggestion to the easiest way for me to move forward?

Best
  Søren

**Comment by michalmuskala** [comment]
Yes. `Jason` does not support decoding directly into data structures - this is one of the biggest differences to `Poison` that we call-out in the [`README`](https://github.com/michalmuskala/jason#differences-to-poison). This is usually better served by another library that can properly handle nested data structures and type validation, such as `Ecto.Changeset`, [`Vex`](https://hexdocs.pm/vex/readme.html), [`Norm`](https://hexdocs.pm/norm/Norm.html), or any similar.
