### ISSUE TITLE
Jason.decode timeouts silently with large files

### ISSUE THREAD

**Issue by herman-rogers** [michalmuskala/jason#154]
So we're processing lots of data and we pull back a record with 300k lines in it. I'd expect Jason parse to just fail or error out but what happens is nothing - it returns and our system continues forward. I tried both Jason.decode! and Jason.decode with the same result. It just stops processing and the program continues. Ideally we'd have an error throw up because of this so we can manage the size.

**Comment by michalmuskala** [comment]
This sounds quite suspicious to me. In particular, there's no place inside of `Jason` where there are any timeouts.

Do you have a way for me to reproduce the issue? I don't think we'll be able to progress much without that

**Comment by herman-rogers** [comment]
Actually coming back to this there might be a performance issue. With jason decode a relatively smallish file takes 3 minutes to parse while Poison.decode takes ~5 to 10 seconds

**Comment by michalmuskala** [comment]
I'd love to get my hands on this file. That indeed sounds like a bug. 

You can send it either here as attachment or to my email michal@muskala.eu

**Comment by michalmuskala** [comment]
Given no progress here, I'm going to close. If you can provide more details, please re-open.
