### ISSUE TITLE
Plan for Jason library after Erlang/OTP 27 added native support to JSON parsing

### ISSUE THREAD

**Issue by prodis** [michalmuskala/jason#185]
Hi @michalmuskala, do you have plans to consume the new Erlang `json` module in `Jason` for future versions?
https://www.erlang.org/blog/highlights-otp-27/#the-new-json-module

The `Jason` DSL with options, encoder protocol and the contract used by other libraries (Postgrex, Phoenix, Plug, etc) is handy. 

The `json` module is faster, but I don't see me using this Erlang module directly in my applications in place of `Jason`.

**Comment by michalmuskala** [comment]
The plan right now is to make a proposal for the Elixir standard library to include an Elixir wrapper around `json` with encoder protocol and interface more similar to `Jason` that's easy to use from Elixir.

**Comment by vanderhoop** [comment]
> The plan right now is to make a proposal for the Elixir standard library to include an Elixir wrapper around json with encoder protocol and interface more similar to Jason that's easy to use from Elixir.

> When this is integrated the Jason library itself would become deprecated.

That approach makes sense long term. In the shorter term, does the approach above imply that there will be at least a 6-month window—until, say, Elixir 1.18—and possibly a 3-year window (when Elixir requires OTP 27+) in which there will be no _drop-in_ solution in the ecosystem for leveraging the new `json` erlang module and its performance gains globally in Phoenix (and other often-JSON-heavy libs in the ecosystem)?

**Comment by michalmuskala** [comment]
Elixir 1.18 RC just shipped with a `JSON` module.

Very likely, once 1.18 is fully released this library will be effectively deprecated.

**Comment by Xunjin** [comment]
@michalmuskala 1.18 is released, we are already in 1.18.2. Should we update the ReadMe to favour using the built-in when 1.18+ ?
