### ISSUE TITLE
Phoenix instructions

### ISSUE THREAD

**Issue by nikolal** [michalmuskala/jason#24]
Hi,

I have hard time connecting Jason with Phoenix app, is there a chance to update docs to include default Phoenix setup file names? The main issue is that I am not sure where to place each part of the code.

I am new to Elixir/Phoenix, so that is probably the reason.

Thanks.

**Comment by michalmuskala** [comment]
I pushed some improvements to the docs, please tell if it's clearer now.

**Comment by nikolal** [comment]
Yes.

Thanks.
