### ISSUE TITLE
protocol Jason.Encoder not implemented

### ISSUE THREAD

**Issue by philippneugebauer** [michalmuskala/jason#32]
Due to some unexpected errors, I got a lot of rollbax crashes and therefore no information about my errors. They weren't sent because of the following:
```
09:40:56.159 [error] GenServer Rollbax.Client terminating
** (Protocol.UndefinedError) protocol Jason.Encoder not implemented for {"id", "2"}, Jason.Encoder protocol must always be explicitly implemented. This protocol is implemented for: Any, Atom, BitString, Date, DateTime, Decimal, Float, Integer, Jason.Fragment, List, Map, NaiveDateTime, Time
    lib/encoder.ex:128: Jason.Encoder.Any.encode/2
    lib/encode.ex:138: Jason.Encode.list/3
    lib/encode.ex:172: Jason.Encode.map_naive_loop/3
    lib/encode.ex:173: Jason.Encode.map_naive_loop/3
    lib/encode.ex:162: Jason.Encode.map_naive/3
    lib/encode.ex:172: Jason.Encode.map_naive_loop/3
    lib/encode.ex:173: Jason.Encode.map_naive_loop/3
    lib/encode.ex:162: Jason.Encode.map_naive/3
```

Is there an easy way of  implementing the encoder for other (standard) types?

**Comment by michalmuskala** [comment]
In general tuples are not encodable to JSON - there is no appropriate general way to represent a tuple - they are not arrays (since we use those for lists) and neither they are objects (since we use them for maps). How would they be represented?

**Comment by philippneugebauer** [comment]
I haven't looked into the code of rollbax, but since I assume that it wants to report an error, why not just treating as string?

**Comment by philippneugebauer** [comment]
After reconsidering it, `rollbax` might be the better place for the fix. I have opened an issue there as well, so we can better discuss the issue: https://github.com/elixir-addicts/rollbax/issues/90
