### ISSUE TITLE
Warn when decoding a map with duplicate atom and string keys 

### ISSUE THREAD

**Issue by AndrewDryga** [michalmuskala/jason#33]
Let's take this map as example:
```
%{"foo" => "bar", :foo => "buz"}
```

When encoding Jason would keep both keys producing an invalid map. Poison did the same, but with Poison ordering was different.
```
iex(6)> Jason.encode!(map)
"{\"foo\":\"bar\",\"foo\":\"buz\"}"
iex(7)> Poison.encode!(map)
"{\"foo\":\"buz\",\"foo\":\"bar\"}"
```

I think we should warn in those cases, otherwise, we going to have issues with decoding:
```
iex(8)> Jason.decode!(Jason.encode!(map))
%{"foo" => "bar"}
iex(9)> Poison.decode!(Poison.encode!(map))
%{"foo" => "buz"}
```
and some JavaScript:
```
# Decode Jason-encoded JSON (notice that it's different from how Jason would decode it)
JSON.parse("{\"foo\":\"bar\",\"foo\":\"buz\"}")
{foo: "buz"}
# Decode Poison-encoded JSON
JSON.parse("{\"foo\":\"buz\",\"foo\":\"bar\"}")
{foo: "bar"}
```

We had a bug where we generated a map with duplicate keys (by reducing it), it worked with Poison because of ordering and stopped after we replaced Poison with Jason. 

I'm not sure if there is any other than emitting a warning way to deal with those through.

**Comment by michalmuskala** [comment]
There's a `Jason.encode(data, maps: :strict)` mode that does this validation and errors in case it would emit duplicate keys. It's slightly slower, though, since it needs to keep track of this.

One thing, I think, that should be looked at in here is making the parsing the same as the javascript parser. This might incur some perf penalty, but I think it's important - there were multiple vulnerabilities in real software because different libraries were parsing JSON differently. Even though, it's not in the standard, I think keeping the last value in case of duplicates is what most libraries do.

**Comment by AndrewDryga** [comment]
I agree. Generally, I expect encoder to match the one in a browser because in most of the cases whatever is encoded sent there.

**Comment by michalmuskala** [comment]
It's not as much about the encoder - there's no way to match the browser since the browser doesn't have a notion of difference between atoms and strings. It's more about the parser giving the same result. In other words, the property I think that should hold is:

```elixir
check all json <- json_with_duplicate_keys() do
  encoded = encode(json)
  assert decode(encoded) === decode(broswer_encode(browser_decode(encoded)))
end
```

**Comment by OvermindDL1** [comment]
> there's no way to match the browser since the browser doesn't have a notion of difference between atoms and strings.

Weeeell Javascript in the browser has the `Symbol` type, which is most like an atom, in addition strings are interned so they are fast identical comparisons (though not fast otherwise if not using `===`), but that still doesn't translate to JSON so it's a side-point about the browser and not JSON...  ^.^;

**Comment by chulkilee** [comment]
From http://json.org/

> An object is an unordered set of name/value pairs

From https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf

> The JSON syntax does not impose any restrictions on the strings used as names, does not require that name strings be unique, and does not assign any significance to the ordering of name/value pairs.

@michalmuskala 

> One thing, I think, that should be looked at in here is making the parsing the same as the javascript parser. This might incur some perf penalty, but I think it's important - there were multiple vulnerabilities in real software because different libraries were parsing JSON differently. Even though, it's not in the standard, I think keeping the last value in case of duplicates is what most libraries do.

I agree that in some cases "de facto" behavior must be honored. However, in this case I'm not clear this is the case for that. Which javascript parser is *the one*? Do "browsers" have their own "standard" on this? If not, why do we need to pick up browser X not Y? What about non-browser cases in this REST API with JSON era? Should we have different modes?

Also fundamentally it is not possible for Jason to know what is the "last" one in a Elixir map. Elixir map uses "the last one" of duplicated keys, but Jason cannot know the "original order" of atom and string key.

```elixir
%{foo: 1, foo: 2}
%{foo: 1} # this is what the doc says

%{"foo" => "string", :foo => "atom"} |> Enum.to_list()
[{:foo, "atom"}, {"foo", "string"}]

[{"foo", "string"}, {:foo, "atom"}] |> Enum.into(%{}) |> Enum.to_list()
[{:foo, "atom"}, {"foo", "string"}]
```

So I believe printing out warning (even non-strict mode) should be the goal at right now.

**Comment by michalmuskala** [comment]
The comment about following behaviour of browsers was specifically about decoding, not encoding. You're right that with encoding and the characteristics of Elixir maps we can't do much.

**Comment by llelf** [comment]
> keeping the last value in case of duplicates is what most libraries do

Are you sure about that? ;)

**Comment by michalmuskala** [comment]
With 7e25ebb8ecf11bf959f805a767661f1c24c2a8fa merged, you can use the option `objects: :ordered_objects` to get all the key values and handle possible duplicates at application level.
