### ISSUE TITLE
Further JSON parsing tests

### ISSUE THREAD

**Issue by aphillipo** [michalmuskala/jason#38]
http://seriot.ch/parsing_json.php

Was reading this on hacker news and thought it was a good set of extra tests that might be useful.

Discussion: https://news.ycombinator.com/item?id=16897061

**Comment by michalmuskala** [comment]
Jason already implements and passes all of the required tests from that suite: https://github.com/michalmuskala/jason/blob/master/test/json_test_suite_test.exs
