### ISSUE TITLE
`Jason.encode` throws `Protocol.UndefinedError`

### ISSUE THREAD

**Issue by tcoopman** [michalmuskala/jason#39]
unexpected behaviour:
`{:error, _} = Jason.encode({:invalid, :value})` throws `Protocol.UndefinedError`. 

I would expect that `encode` returns an error tuple. Is there a reason that `Jason.Encode.encode` doesn't catch this error?

**Comment by michalmuskala** [comment]
I agree this should be corrected. Thank you for pointing this out.

**Comment by michalmuskala** [comment]
Fixed in https://github.com/michalmuskala/jason/commit/ad0f57b116640153dcf4ec7c3d8aa76d43912e69
