### ISSUE TITLE
Add ability to preserve atoms in decode. 

### ISSUE THREAD

**Issue by kraythen** [michalmuskala/jason#44]
We should be able to send a flag to the decoder that will preserve atoms. So when they are written they will be written with the `:` in front of them and when they are read, if there is a leading : it should be read back as an atom. The user should be able to use only existing atoms as well and the code should throw if the atom doesn't exist. I would recommend something like an option atoms with the possible values of :none (the default now), `:create` which will call `string_to_atom` on decode and `:existing` which will call `string_to_existing_atom` on decode. The encoder should also be able to take such an option.

**Comment by michalmuskala** [comment]
Even if we implemented this, there are much more Elixir types that we can't represent cleanly in JSON - tuples, datetimes, unlimited integers, not to mention things like pids, references and all the other very elixir/erlang specific things.

Maybe an answer would be a higher-level encoding scheme building on top of raw JSON like [transit](https://github.com/cognitect/transit-format) popular in the Clojure world. I'm convinced the answer isn't intertwining this with a JSON decoder.
