### ISSUE TITLE
Using jason in hex packages and the trouble with structs

### ISSUE THREAD

**Issue by minhajuddin** [michalmuskala/jason#46]
I really love the speed of Jason :smile: . However, I am having trouble with the default implementation while using it in hex packages https://github.com/honeybadger-io/honeybadger-elixir/issues/160 . How can I use `jason` while still being able to encode json for arbitrary structs that are passed?

**Comment by nihalgonsalves** [comment]
I was thinking, maybe a `defimpl` could help:

```ex
defimpl Jason.Encoder, for: [Map] do
  def encode(%_{} = struct, opts) do
    # pipe through Map.from_struct before passing onto the default implementation
  end
  def encode(map, opts) do
    # pass on to default implementation
  end
end
```

I haven't tested this, but this should make it possible without implementing a deep `Map.from_struct/1`.

**Comment by michalmuskala** [comment]
`Jason` does not define a way to encode arbitrary structs - they always need to be explicitly encoded by either manually encoding to a map (for example by using `Map.from_struct`) or by deriving the `Jason.Encoder` protocol. In general, there are many more types that cannot be just encoded to JSON, so tools shouldn't assume they can throw anything at the JSON encoder - some examples are tuples, bitstrings (that are not binaries), pids, ports, references and even binaries that are not UTF-8 encoded. I don't think it's correct for a tool to just try to encode arbitrary data to JSON by passing it to the encoder. If the tool does not want to require users pass JSON-encodable data to it, to should do some pruning and sanitising before encoding.

**Comment by minhajuddin** [comment]
For future searchers, we've done this using a custom module which loops through the data and encodes it using Jason: https://github.com/honeybadger-io/honeybadger-elixir/blob/master/lib/honeybadger/json.ex
