### ISSUE TITLE
Support for encoding maps with structs as keys

### ISSUE THREAD

**Issue by ConnorRigby** [michalmuskala/jason#47]
https://github.com/michalmuskala/jason/blob/master/lib/encode.ex#L241-L244

It'd be nice for this function to have one more clause:
```elixir
  def key(%{__struct__: module} = struct, escape) do
  end
```

and try to attempt to encode it.

**Comment by michalmuskala** [comment]
Jason uses the `String.Chars` protocol for encoding keys, so you can implement it for your struct and it should be properly encoded as a key.

**Comment by ConnorRigby** [comment]
Yeah i noticed that. In my particular case i need to encode my struct as an integer. Feel free to close if you don't think this is a valid feature for Jason. I know it's sort of a weird one.

**Comment by michalmuskala** [comment]
JSON only allows strings as keys, so a custom protocol for the keys wouldn't help much - it has to be a string at the end.

**Comment by ConnorRigby** [comment]
Oh interesting. Thanks!

**Comment by michalmuskala** [comment]
I'm going to close this. Please reopen if there are some more issues.
