### ISSUE TITLE
Support to skip few fields globally if having certain value

### ISSUE THREAD

**Issue by tanweerdev** [michalmuskala/jason#53]
Support to skip few fields globally if having certain value e.g `Ecto.Association.NotLoaded`
because if we write customer encoder and return nil for `Ecto.Association.NotLoaded`, this is totally incorrect

**Comment by michalmuskala** [comment]
I don't think it's a job of the json encoder to do this. There should be another layer that prepares data for encoding. This can be either the encoder protocol or something like phoenix views.

Additionally such a feature wouldn't be practical - it would significantly slow things down.
