### ISSUE TITLE
(optional) HiPE support

### ISSUE THREAD

**Issue by jjl** [michalmuskala/jason#57]
I think we should provide HiPE support. I was thinking something like this in the modules where it would make sense:

```elixir
if System.get_env("JASON_HIPE") do
  @compile :native
  @compile {:hipe, [:verbose, :o3]}
end
```

Thoughts? This may perhaps become less relevant if #9 happens.

**Comment by josevalim** [comment]
The compilation of any lib as hipe can be done like this:

```elixir
ERL_COMPILER_OPTIONS="+native" mix deps.compile some_lib
```

It can also be done as a separate pass during releases (if the releases tool support it). In a nutshell, I don't think it is up to the library to add those conditional, but rather the tooling should support it.

For example, someone can also make a `mix hipe` task that accepts a library or a module and does all of the above for you. Imagine something like:

    mix hipe --app foo

Or:

    mix hipe --module MyApp.Bar
