### ISSUE TITLE
encoding keywordlists

### ISSUE THREAD

**Issue by isaac-rstor** [michalmuskala/jason#60]
I find that I'm filtering maps before marshalling data in the encoder.  This requires me to do an `Map.into(%{})` before sending it to `|> Jason.Encode.map`
Do you think it would be worth doing a `Jason.Encode.keyword`?
would be happy to PR it myself.

**Comment by michalmuskala** [comment]
Yes, i think that's reasonable. PR welcome 🙂

**Comment by isaac-rstor** [comment]
https://github.com/michalmuskala/jason/pull/61

**Comment by michalmuskala** [comment]
Closed by https://github.com/michalmuskala/jason/commit/cb1f26a8b3ca7efd4c79437b803cd8021c57d204
