### ISSUE TITLE
Cannot encode because the association was not loaded

### ISSUE THREAD

**Issue by pavlov33** [michalmuskala/jason#63]
It's pretty annoying that I always need to preload associations for structs before encoding.
Is there some way to just skip certain field if it was not loaded?

Related error says:
`Or choose to not encode the association when converting the struct to JSON by explicitly listing the JSON fields in your schema`
It's definitely not solution for me because I need sometimes either struct with associations and without to encode

**Comment by josevalim** [comment]
@pavlov33 that's not an issue with Jason.

If you have to render it sometimes with the field and sometimes without, then you write the logic accordingly. If you are using Phoenix, one option is to have two different views to render json. If not, it is as simple as having two clauses:

```
def my_data_to_json(data, true = _include_associations?) do
  Map.take(data, [:foo, :bar, :association])
end

def my_data_to_json(data, false = _include_associations?) do
  Map.take(data, [:foo, :bar])
end
```

**Comment by edgarjrg** [comment]
thank you for your answer @josevalim , i'm still quite lost how to implement that in this situation (still very new to Elixir).

./lib/destiller/problem.ex
```
defmodule Destiller.Problem do
  use Ecto.Schema
  import Ecto.Changeset

  @derive {Jason.Encoder, only: [:id, :title, :repositories]}
  schema "problems" do
    field(:title, :string)

    many_to_many(:repositories, Destiller.Repository,
      join_through: Destiller.ProblemRepository,
      on_replace: :delete,
      on_delete: :delete_all
    )

    timestamps()
  end

  @doc false
  def changeset(prolem, attrs) do
    prolem
    |> cast(attrs, [:title])
    |> validate_required([:title])
  end
end
```

Sometimes i query with and without the associations, that means i can not use the `@derive` macro? how can i implement the two protocols?
