### ISSUE TITLE
Syntax error reported for perfectly valid json

### ISSUE THREAD

**Issue by cruisemaniac** [michalmuskala/jason#66]
For the code snippet below:
```
 %{id: complex.id,
      name: complex.name,
      street: complex.street,
      locality: complex.locality,
      city: complex.city,
      state: complex.state,
      pincode: complex.pincode,
      test_payload: {
        test_key: "test_value"
      }
```

Phoenix framework reports a syntax error before: `test_key`

The JSON rendered if I remove the sub section (`test_payload`) and directly list the `test_key` is valid however.

**Comment by tcoopman** [comment]
You need to add a `%` sign before the `{` to have a valid elixir map.

**Comment by cruisemaniac** [comment]
what a royal doofus I was! Thanks for this. Not a bug!

Closing.
