### ISSUE TITLE
Proposal: NaN handling

### ISSUE THREAD

**Issue by arnomi** [michalmuskala/jason#68]
Hi all,

while the JSON spec doesn't support the handling of NaNs or +-Infinity, quite a few JSON parsers (most notably the default python parser) support these by default. Consider, for example, the following python snippet:

```
>>> import json
>>> data =  [float('nan'), float('inf'), float('-inf')]
>>> data
[nan, inf, -inf]
>>> json.dumps(data)
'[NaN, Infinity, -Infinity]'
```

While this is not conforming to spec, it is something we need to deal with when integrating against services that we do not control. 

Currently, I am not aware of any nice workarounds. Thus, I would like to propose a small extension to Jason to allow handling such cases. A quick look at the decoder suggests that adding handlers for 'NaN', "Infinity" and '-Infinity' would be straight forward. This could also be controlled by a decoding option whether or not to decode such json (default should be false). Internally, these could be mapped to atoms. Since this branch is only triggered in "error cases", this change would not have any impact on performance for json that follows the spec.

On encoding, as far as I see, all that would be needed would be a custom escape function.

Looking forward to feedback.

**Comment by hauleth** [comment]
@arnomi send strings in case of "floating-point" special cases instead of relying on JSON extensions.

**Comment by OvermindDL1** [comment]
For note:

RFC 7159 states:

> Numeric values that cannot be represented in the grammar below (such as Infinity and NaN) are not permitted.

Not only are they not allowed, they are *specifically* disallowed.

For note, javascript parses a structure containing NaN/-Infinity/+Infinity to JSON by converted those values to `null`, and it will not accept (exceptions) a JSON structure containing them.

**Comment by arnomi** [comment]
@OvermindDL1 @hauleth 
I agree with both of you that you usually should not do that. The issue is, that the default Python as well as some c++ parsers allow for that (often by default). Thus, if you do not control the other side, i.e., the json generating side, there is not much you can do. 

It also doesn't help to state that Python is just wrong for implementing an encoder that doesn't conform to the spec. We somehow need to deal with that. Thus, my proposal is to have Jason by default follow the spec, but allow for having the option to not break on those (very common) cases.

**Comment by OvermindDL1** [comment]
However, if the reference parser itself, the Javascript parser, the most used JSON parser in existence, will exception on such values, then why would it be good to allow for those values, even optionally, as that would fragment the spec.

https://tools.ietf.org/html/draft-thomson-postel-was-wrong-02

By allowing it in one place then that encourages sloppy implementations, thus meaning that they *will* fail in other places, especially considering that it would fail very badly in the most used json parser currently in existence that is not good for reliability.

In addition, it would add needless slowdown to the JSON parser here (already one of the slowest parts of the pipeline in heavy JSON API's) if it is a runtime optiona, and if it is a compile-time option then that could very easily break invariants in other libraries using Jason in the same program that expect following the Spec.

Regardless of what Python does this seems way too high of a cost to support in the primary JSON parser used in the Phoenix world.  Why not use another parser that is specifically standards non-conforming instead?  Maybe a YAML parser (which is a super-set of json) might already support it?

**Comment by OvermindDL1** [comment]
Here's even a javscript session in the console of this github page right now:
```javascript
> JSON.parse('{"a": 42}')
{a: 42}

> JSON.parse('{"a": NaN}')
VM59484:1 Uncaught SyntaxError: Unexpected token N in JSON at position 6
    at JSON.parse (<anonymous>)
    at <anonymous>:1:6
```
If javascript *itself* can't even parse it, then it doesn't seem even remotely safe not to follow the same pattern.

**Comment by arnomi** [comment]
True, the javascript default parser doesn't support it. Here are a few parsers that do:

- Python (default parser)
- GSON (one of the main JSON libs on the JVM). From GSON docs
>>> Section 2.4 of JSON specification disallows special double values (NaN, Infinity, -Infinity). However, Javascript specification (see section 4.3.20, 4.3.22, 4.3.23) allows these values as valid Javascript values. Moreover, most JavaScript engines will accept these special values in JSON without problem. So, at a practical level, it makes sense to accept these values as valid JSON even though JSON specification disallows them.
- OCaml Yojson (allows NaN by default)
- Julia (see also [issues/168](https://github.com/JuliaIO/JSON.jl/issues/168))

So, while I agree that the default should be to be spec compliant, it is similarly important to be practical. 
NaNs and Infinity are very handy in mathematical contexts which is also recognized by the IEEE754 standard for floats. Many parsers recognize this by being practical and allowing to cater for this case via an option flag. 

And as to slowness: the implementation in Jason could be such that it has no performance impact on spec compliant json. All that would be needed is to allow the user to deal with "errors" on the decoding part and how to escape atoms on the encoding part.

**Comment by OvermindDL1** [comment]
Note what GSON said there, the Javascript specification allows it, but JSON is not Javascript, in addition `Moreover, most JavaScript engines will accept these special values in JSON without problem` is entirely wrong as the Spec states that javascript's `JSON.parse` will not accept it and none of Chrome, Firefox, or Edge accept it (I'm not sure of any other big browsers that I could test?).  So it seems that GSON accepts javascript notation, not JSON, those are two different specs, and if it is called JSON then it should follow JSON or people can start getting very unexpected errors and surprises.

yojson like python has an option to follow the json spec, when `std=false` then it follows javascript syntax, not json.

Never used julia so no clue about it (isn't a lot of it based on python though?).

Regardless, JSON does not support `nan`/`-inf`/`+inf`, if you need those then why not encode is as a string or use some other encoding that does support it, such as the erlang's own term format or messagepack or whatever.  If mathematical accuracy is needed then JSON is insufficient for encoding floats anyway as it doesn't support float hex notation unless that is to be stuffed into a string as well, it is a very basic format.

But still, if you need a JSON library that is not JSON, then why not use another, one that specifically states that it is not JSON?

_/me really *really* doesn't want surprises even having a chance of being parsed_

**Comment by dch** [comment]
My 0.02c is that the default behaviour of a JSON compliant parser should be 100% spec compliance.

Nothing against having toggles in the interests of wider compatibility, but my experience shows that this leads in the long term to problems, which is why we worked on the i-json spec https://tools.ietf.org/html/rfc7493 (reference to https://en.wikiquote.org/wiki/Andrew_S._Tanenbaum quote).

@arnomi has the current strict compliance caused specific issues for inter-op for you?

**Comment by arnomi** [comment]
Yes, we are interfacing with a python component that produces json with NaNs. And the only way to properly parse this data is to have an "extended json parser" that allows for spec extensions. 

Since there are so many libraries out there that do not always follow the spec (many even by default) I think the only pragmatic way to achieve interoperabilty is to allow for custom extensions. Imo, such an extension mechanism should even make it back into the JSON spec.

**Comment by OvermindDL1** [comment]
> produces json with NaNs

Then it's not JSON.

> And the only way to properly parse this data is to have an "extended json parser" that allows for spec extensions.

Then it is some other format that is not JSON, which is entirely fine to use, but it shouldn't be called JSON as that invites ambiguity, like what python is doing.

> Imo, such an extension mechanism should even make it back into the JSON spec.

Except they become useless for a communication format as you can only assume the minimum feature-set unless you start setting up negotiation of types and use them when possible else fallback to, again, the minimum feature-set, and adding a feature-type header to all json makes it backwards type incompatible so it would have to be done at a higher level that is outside of JSON regardless, in which case just use something other than JSON, like msgpack is popular.

**Comment by hauleth** [comment]
> something other than JSON

Erlang already provides great format for data, which is quite terse and at the same time quite powerful [ETF](http://www.erlang.org/doc/man/erl_ext_dist.html).

**Comment by arnomi** [comment]
> Then it is some other format that is not JSON, which is entirely fine to use, but it shouldn't be called JSON as that invites ambiguity, like what python is doing.

A good thing that the library is called Jason then.

**Comment by arnomi** [comment]
Overall, I think we can close the issue here.

**Comment by OvermindDL1** [comment]
> A good thing that the library is called Jason then.

Jason is not a format spec though, it's a library to implement the JSON spec so as to be compatible with the JSON standard such as with Javascript's `JSON.parse` and so forth.  ^.^
