### ISSUE TITLE
Move to Erlang 

### ISSUE THREAD

**Issue by lpil** [michalmuskala/jason#70]
Hello! This may seem an obnoxious suggestion but it is intended to be both friendly and perfectly dismissable :)

Would it be possible to convert this library to Erlang and rebar3? I ask because I believe this to be the best JSON encoding/decoding library available in the ecosystem, and Erlang/LFE/Alpaca/Gleam etc users would benefit tremendously from it.
It is currently possible to use the Elixir library but having to pull in the Elixir compiler and stdlib will deter many users.

See also: The telemetry library, which recently went through the same transition https://github.com/beam-telemetry/telemetry/issues/20

Thank you :)

**Comment by michalmuskala** [comment]
Jason leverages Elixir features extensively. Macros are used for code-generation to produce the most efficient code. Moving to Erlang would probably require some additional scripting to generate the Erlang code, which IMO would increase the complexity of the implementation considerably.
The bigger issue, though, is that the user interface of Jason is heavily based on protocols, which are not available in Erlang - moving to Erlang would mean abandoning that part of the library.

This is contrary to Telemetry, that did not use Elixir-specific features extensively.

**Comment by lpil** [comment]
From a look over the source code this is what I suspected, though thought it was worth asking. Thank you
