### ISSUE TITLE
Decimal quotes will prevent this library from being used internationally for healthcare :(

### ISSUE THREAD

**Issue by DarkMarmot** [michalmuskala/jason#81]
I understand the reasons you've not implemented this as listed at: 

https://github.com/michalmuskala/jason/issues/71

The international standard for medical messages is currently moving to FHIR: http://hl7.org/fhir/

They’ve made certain… poor choices (like not including the version id in any message documents).

One of these is that if a message is delivered in JSON format, floats must be encoded as numbers in the JSON with precision preserved. 

I know this breaks generic encode/decode round-trip systems, but alas, it's the standard we have to adhere to for medicine. And yes, it's really stupid :(

Do you think I should make a 'healthcare' fork of your library instead of trying to get the option added?

**Comment by DarkMarmot** [comment]
Nevermind -- I think I have a solution! :)

Using the helpful code from issue 71 -- one can wrap Decimal in a custom module to implement the protocol as an override! yay! :)

```defimpl Jason.Encoder, for: FHIR.Decimal do
  def encode(decimal, _opts) do
    Decimal.to_string(decimal.decimal, :normal)
  end
end
```

**Comment by DarkMarmot** [comment]
So, I found I needed to hack the Decoder a tiny bit in order to read numbers as strings (otherwise, numeric information is lost...) 

I'd love to have this as an option (I know, a _terrible and evil option_) in Jason and would happily submit a PR if you're amenable.

Otherwise, I fear I'll have to create a fork to host a Lossless_Jason for everyone who's trapped with the aberrant horrors of "standards" like FHIR. :(

**Comment by DarkMarmot** [comment]
P.S. I enjoyed digging through your code! lots of tricks and syntax I hadn't used before! :)

**Comment by OvermindDL1** [comment]
Could be useful for some fields, like that (broken) new medical spec, for numbers to be read from and to Decimal instead of BEAM floats with a given option or new code path to call?

**Comment by CharlesOkwuagwu** [comment]
@DarkMarmot I find myself in a similar situation that requires decimals in json to not be strings.
I have applied a similar solution to yours, but I loose the decimal places I had specified.

For example where I have  `Decimal.new("1000.00"`), Jason returns it just `1000`

Please do you have a solution for this?

Thanks

**Comment by DarkMarmot** [comment]
> @DarkMarmot I find myself in a similar situation that requires decimals in json to not be strings.
> I have applied a similar solution to yours, but I loose the decimal places I had specified.
> 
> For example where I have `Decimal.new("1000.00"`), Jason returns it just `1000`
> 
> Please do you have a solution for this?
> 
> Thanks

After having failed to get other parties to change their standards -- and seeing that libraries in other languages like C# support this functionality, I feel it's a real issue for Elixir to have a pretty "standard" library that doesn't have a way to support this. 

If Jason doesn't move to do so, I will open source a fork of it that handles this (I had really wanted to avoid that route, but it seems like enough people need it that it should be out there).

The easiest hack I found to preserve the data (though, ideally, it should be configurable at parse I think) -- is to hack the library in `decoder.ex`, preserving floats at strings:

```
  defp try_parse_float(string, _token, _skip) do
    string
    #    :erlang.binary_to_float(string)
    #  catch
    #    :error, :badarg ->
    #      token_error(token, skip)
  end
```

I ended up needing to store an intermediate data format for my use case, which Jason happily supports with encoder protocols, e.g.:

```

defmodule MyProject.Decimal do
  defstruct value: nil

  def new(value) when is_binary(value) do
    %MyProject.Decimal{value: value}
  end
end

defimpl Jason.Encoder, for: MyProject.Decimal do
  def encode(decimal, _opts) do
    Decimal.to_string(Decimal.new(decimal.value), :normal)
  end
end

```

**Comment by conradfr** [comment]
> Did you do manage to do it without forking?

What I meant is that I used Decimal.to_float() on my code, which was not that much of an inconvenience because I was doing some transform / data marshaling and not using the "jason data" straight.

So I didn't fork it because my use case was simpler and needed once (so far).

**Comment by DarkMarmot** [comment]
> > Did you do manage to do it without forking?
> 
> What I meant is that I used Decimal.to_float() on my code, which was not that much of an inconvenience because I was doing some transform / data marshaling and not using the "jason data" straight.
> 
> So I didn't fork it because my use case was simpler and needed once (so far).

Yeah, I was building a library so I needed to support to/from JSON roundtrips with identical results. Having  decoding options would really facilitate this for edge case needs I think.

**Comment by DarkMarmot** [comment]
It also appears that some work is going into this now. Wish this hadn't been denied as a feature back when... but hope:
https://github.com/michalmuskala/jason/pull/115

**Comment by michalmuskala** [comment]
With #115 merged, I believe all outstanding issues raised here have a way to be solved.
